apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentblue #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  labels:
    app: nginx-app
spec:
  replicas: 2 #The number of pods to be created in the 
   #Kubernetes cluster for the nginx application container
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app 
    spec:
      containers:
      - name: nginx-app #The name of the nginx application container
        #The Docker image for building the nginx application container
        image: nginx:latest 
        ports:
        - containerPort: 80 #The port for the nginx application container
