apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes 
        #Deployment to be created in the Kubernetes cluster
  labels:
    app: busybox-app
spec:
  replicas: 2 #The number of pods to be created in the 
   #Kubernetes cluster for the busybox application container
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app 
    spec:
      containers:
      - name: busybox-app #The name of the busybox application container
        #The Docker image for building the busybox application container
        image: busybox:latest 
        ports:
        - containerPort: 3000 #The port for the busybox application container